### ISSUE TITLE
Request blocked by CORS policy

### ISSUE THREAD

**Issue by lolero** [aloysius-pgast/bittrex-signalr-client#25]
Hi,

I am trying to use your library to stream some bittrex data to a React application but when I try to have the client subscribe to a pair, I get the following error

`Access to fetch at 'https://bittrex.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Do you know how I can solve this problem?

Cheers!

**Comment by aloysius-pgast** [comment]
Hi. Can you confirm that you're using the library server-side, in a nodejs application and not client side in the browser ?

**Comment by lolero** [comment]
No, I want to use it on the client.  I want to write a small serverless application to chart and view streaming data from different markets.

**Comment by aloysius-pgast** [comment]
Sorry, this library is only meant to be used on server side, in a nodejs application. I cannot offer any kind of support for client side usage (not even sure it would work)

**Comment by aloysius-pgast** [comment]
Did you check https://github.com/aloysius-pgast/crypto-exchanges-gateway ? It can handle the server part and already integrate various exchanges

**Comment by lolero** [comment]
Ok, thanks! :)
