### ISSUE TITLE
How to Use Bittrex Websocket V3 "Tickers" Subscription?

### ISSUE THREAD

**Issue by baloian** [aloysius-pgast/bittrex-signalr-client#29]
Hi @aloysius-pgast ,

I would like to use a new Bittrex API V3, particularly, tickers subscription. Currently, I do the following

```
let client = new SignalRClient({
  pingTimeout: 5000,
});
  
client.on('ticker', (data: any) => {
  console.log(data)
});

client.subscribeToAllTickers();
 
```

Looks like I am getting real-time data, but not sure if this uses the V3 API. s this the right way to do it?

**Comment by aloysius-pgast** [comment]
Hi. Library is currently using v1.1, not v3

**Comment by aloysius-pgast** [comment]
I'll try to move to v3 before EOL planned for 2020-09-30 (at least for public streams)

**Comment by baloian** [comment]
@aloysius-pgast thanks! I am closing this and will follow upcoming updates.
