### ISSUE TITLE
Can I subscribe to all the tickers on Bittrex?

### ISSUE THREAD

**Issue by ProgrammingLife** [aloysius-pgast/bittrex-signalr-client#3]
Can I subscribe to all the tickers on Bittrex?

**Comment by aloysius-pgast** [comment]
Hi. I’ll try to add new method to subscribe to all tickers in next version.

**Comment by aloysius-pgast** [comment]
Hi
Please use method _subscribeToAllTickers_ to subscribe to all tickers. Keep in mind that after calling this method it won't be possible to subscribe to tickers individually without calling _unsubscribeFromAllTickers_ first
